name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: '*/30 * * * 1-5'

jobs:
  call-licensed:
    name: Licensed
    uses: actions/reusable-workflows/.github/workflows/licensed.yml@main
